<?
	define("HIDE_SIDEBAR", true);
	
	require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");

	$APPLICATION->SetTitle("Заказы");

	$APPLICATION->IncludeComponent(
		"bitrix:sale.order.ajax",
		"custom-order",
		Array(
			"ACTION_VARIABLE" => "soa-action",
			"ADDITIONAL_PICT_PROP_14" => "-",
			"ADDITIONAL_PICT_PROP_15" => "-",
			"ALLOW_APPEND_ORDER" => "Y",
			"ALLOW_AUTO_REGISTER" => "Y",
			"ALLOW_NEW_PROFILE" => "N",
			"ALLOW_USER_PROFILES" => "N",
			"BASKET_IMAGES_SCALING" => "adaptive",
			"BASKET_POSITION" => "before",
			"COMPATIBLE_MODE" => "Y",
			"COUNT_DELIVERY_TAX" => "N",
			"COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
			"DELIVERIES_PER_PAGE" => "8",
			"DELIVERY_FADE_EXTRA_SERVICES" => "N",
			"DELIVERY_NO_AJAX" => "Y",
			"DELIVERY_NO_SESSION" => "Y",
			"DELIVERY_TO_PAYSYSTEM" => "d2p",
			"DISABLE_BASKET_REDIRECT" => "N",
			"EMPTY_BASKET_HINT_PATH" => "/",
			"MESS_DELIVERY_CALC_ERROR_TEXT" => "Вы можете продолжить оформление заказа, а чуть позже менеджер магазина свяжется с вами и уточнит информацию по доставке.",
			"MESS_DELIVERY_CALC_ERROR_TITLE" => "Не удалось рассчитать стоимость доставки.",
			"MESS_FAIL_PRELOAD_TEXT" => "Вы заказывали в нашем интернет-магазине, поэтому мы заполнили все данные автоматически.<br />Обратите внимание на развернутый блок с информацией о заказе. Здесь вы можете внести необходимые изменения или оставить как есть и нажать кнопку \"#ORDER_BUTTON#\".",
			"MESS_SUCCESS_PRELOAD_TEXT" => "Вы заказывали в нашем интернет-магазине, поэтому мы заполнили все данные автоматически.<br />Если все заполнено верно, нажмите кнопку \"#ORDER_BUTTON#\".",
			"ONLY_FULL_PAY_FROM_ACCOUNT" => "N",
			"PATH_TO_AUTH" => "/auth/",
			"PATH_TO_BASKET" => "/personal/cart/",
			"PATH_TO_ORDER" => "/personal/order/make/",
			"PATH_TO_PAYMENT" => "/personal/order/payment/",
			"PATH_TO_PERSONAL" => "/personal/order/",
			"PAY_FROM_ACCOUNT" => "Y",
			"PAY_SYSTEMS_PER_PAGE" => "8",
			"PICKUPS_PER_PAGE" => "5",
			"PRODUCT_COLUMNS_HIDDEN" => array("PREVIEW_PICTURE", "DETAIL_PICTURE", "PREVIEW_TEXT", "PROPS", "NOTES", "DISCOUNT_PRICE_PERCENT_FORMATED", "PRICE_FORMATED", "WEIGHT_FORMATED", "PROPERTY_OTHER_PICTURES", "PROPERTY_BLOG_POST_ID", "PROPERTY_BLOG_COMMENTS_CNT", "PROPERTY_ADVANTAGES", "PROPERTY_CML2_ARTICLE", "PROPERTY_CERTIFICATES", "PROPERTY_DELIVERY", "PROPERTY_GUARANTEE", "PROPERTY_FAVORITES", "PROPERTY_STATUS", "PROPERTY_BRAND", "PROPERTY_HARDNESS", "PROPERTY_FORM", "PROPERTY_TYPE", "PROPERTY_BRACING_TYPE", "PROPERTY_DECOR", "PROPERTY_VLAGA", "PROPERTY_SIZE", "PROPERTY_PROPS"),
			"PRODUCT_COLUMNS_VISIBLE" => array("PREVIEW_PICTURE", "DETAIL_PICTURE", "PREVIEW_TEXT", "PROPS", "NOTES", "DISCOUNT_PRICE_PERCENT_FORMATED", "PRICE_FORMATED", "WEIGHT_FORMATED", "PROPERTY_OTHER_PICTURES", "PROPERTY_BLOG_POST_ID", "PROPERTY_BLOG_COMMENTS_CNT", "PROPERTY_ADVANTAGES", "PROPERTY_CML2_ARTICLE", "PROPERTY_CERTIFICATES", "PROPERTY_DELIVERY", "PROPERTY_GUARANTEE", "PROPERTY_FAVORITES", "PROPERTY_STATUS", "PROPERTY_BRAND", "PROPERTY_HARDNESS", "PROPERTY_FORM", "PROPERTY_TYPE", "PROPERTY_BRACING_TYPE", "PROPERTY_DECOR", "PROPERTY_VLAGA", "PROPERTY_SIZE", "PROPERTY_PROPS"),
			"PROPS_FADE_LIST_1" => array("1", "2", "3", "4", "5", "6", "7"),
			"PROPS_FADE_LIST_2" => array("8", "9", "10", "11", "12", "13", "14", "15", "16", "17"),
			"PROPS_FADE_LIST_3" => array("18", "19", "20", "21", "22", "23", "24", "25", "26"),
			"PROP_1" => array(),
			"SEND_NEW_USER_NOTIFY" => "Y",
			"SERVICES_IMAGES_SCALING" => "adaptive",
			"SET_TITLE" => "Y",
			"SHOW_ACCOUNT_NUMBER" => "Y",
			"SHOW_BASKET_HEADERS" => "N",
			"SHOW_COUPONS_BASKET" => "Y",
			"SHOW_COUPONS_DELIVERY" => "Y",
			"SHOW_COUPONS_PAY_SYSTEM" => "Y",
			"SHOW_DELIVERY_INFO_NAME" => "Y",
			"SHOW_DELIVERY_LIST_NAMES" => "Y",
			"SHOW_DELIVERY_PARENT_NAMES" => "Y",
			"SHOW_MAP_FOR_DELIVERIES" => array("2", "3", "4", "5", "6"),
			"SHOW_MAP_IN_PROPS" => "Y",
			"SHOW_NEAREST_PICKUP" => "N",
			"SHOW_NOT_CALCULATED_DELIVERIES" => "L",
			"SHOW_ORDER_BUTTON" => "final_step",
			"SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
			"SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
			"SHOW_STORES_IMAGES" => "Y",
			"SHOW_TOTAL_ORDER_BUTTON" => "N",
			"SHOW_VAT_PRICE" => "Y",
			"SKIP_USELESS_BLOCK" => "Y",
			"SPOT_LOCATION_BY_GEOIP" => "Y",
			"TEMPLATE_LOCATION" => "popup",
			"TEMPLATE_THEME" => "site",
			"USER_CONSENT" => "N",
			"USER_CONSENT_ID" => "1",
			"USER_CONSENT_IS_CHECKED" => "N",
			"USER_CONSENT_IS_LOADED" => "N",
			"USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
			"USE_CUSTOM_ERROR_MESSAGES" => "N",
			"USE_CUSTOM_MAIN_MESSAGES" => "N",
			"USE_PHONE_NORMALIZATION" => "Y",
			"USE_PRELOAD" => "Y",
			"USE_PREPAYMENT" => "N",
			"USE_YM_GOALS" => "N"
		)
	);
	
	require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");
?>